### ISSUE TITLE
Can't Format to page (program)

### ISSUE THREAD

**Issue by Ghosted00** [D1firehail/AdeptiScanner-GI#11]
Can't get program to format to page after extracting and running. not the game.

**Comment by D1firehail** [comment]
I'm not sure what you mean by that, do you have a more detailed explanation or maybe an image?

**Comment by Ghosted00** [comment]
After Extracting latest version of the program, it's cut off at top of screen and won't fit within the boundaries of screen. I am currently downloading Genshin to my PC and will run the program after it installs. Atm it's only on Playstation. Sorry, I've stepped away from the PC or I would send a image. It's probably something I'm doing wrong. Thanks for the Response! Will test and research a bit and update this post.

**Comment by D1firehail** [comment]
Your problem is probably screen size, since Adeptiscanner isn't designed for resolutions below 1080p. The default window size of the scanner is 800 x 820, with an enforced minimum size of 650 x 600. If the top is off-screen, you should still be able to move the scanner window with `Windows key + Arrows`.

If you have multiple monitors it could probably still be work. The game needs to be in windowed mode, but it not being exactly 1600x900 shouldn't be a problem. Worst case you might get some accuracy issues but it's probably fine.

**Comment by Ghosted00** [comment]
Oh! OK yeah my resolution is 1080p so I'll use windows Key to adjust it out. Thanks! You can close this out if you like
