### ISSUE TITLE
Maiden beloved

### ISSUE THREAD

**Issue by serge42** [D1firehail/AdeptiScanner-GI#15]
Why the ArtifactInfo.json set labels were all changed to MaidenBeloved, here: 909ab662280882f25766b3b379e076c71fa034b4?
now every artifacts is maiden beloved :(

**Comment by D1firehail** [comment]
Please check your calendar, should be fixed in about a day.

You can also manually change the data file, there are [instructions in the readme](https://github.com/D1firehail/AdeptiScanner-GI#updating-for-a-new-version) and the [previous version of the file can be found here.](https://github.com/D1firehail/AdeptiScanner-GI/blob/20d47ded596d5aea901d327aefa89cf31a071719/AdeptiScanner%20GI/ScannerFiles/ArtifactInfo.json)

**Comment by serge42** [comment]
Bruh! you got me there ヽ(`д´；)/

I changed back to previous thx

**Comment by D1firehail** [comment]
The change has now been reverted
