### ISSUE TITLE
small monitor issues

### ISSUE THREAD

**Issue by AliasTron7** [D1firehail/AdeptiScanner-GI#9]
My monitor supports [1440x900] resolution now If I make it windowed in [1366x768] resolution as I don't have 1600X900 windowed option  still the app is not completely fitting on the screen to capture artifacts is there a solution or I need to upgrade my monitor ..!

**Comment by D1firehail** [comment]
Currently, you won't be able to use Adeptiscanner with only that monitor. Can't make any promises when I get the time to do the below stuff, so you might want to check if any of the other scanners would work for you right now.

There are some improvements to the capture process I am considering that would make it work with sub-1080p monitors.

I'm unsure if I can (and want to) make it work with fullscreen along with those possible improvements, which would cap you at 1366x768. I'll look into it, though.

1366x768 had some accuracy problems in the past, but some of the more recent versions have made improvements that may have mostly solved that. 

If fullscreen support is added, there is a slight risk 1440x900 still won't work due to being a different aspect ratio than what I have available to test, but it's relatively likely to work.

**Comment by AliasTron7** [comment]
thank you for the clarification

**Comment by D1firehail** [comment]
V1.5.0 adds support for both fullscreen and lower resolutions
